BMI calculator added
PureFour/workout-rival-backend pull request #38
Opened 2020-09-29 16:43 UTC by JakubiM

2020-09-29 16:48 UTC, PureFour requested changes

2020-09-29 16:48 UTC, PureFour commented on src/main/java/com/ruczajsoftware/workoutrival/service/UserService.java
> +    public float getUserBMI(String username) throws EntityNotFoundException, BadRequestException {
Testy ;)

2020-10-03 14:18 UTC, PureFour requested changes
Gdzie te testy!?

2020-10-18 14:50 UTC, michaljk1 approved these changes

2020-10-18 14:52 UTC, PureFour approved these changes

2020-10-18 14:53 UTC, merged